name: Build and Push Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up SSH agent with your private key
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3.1.0
        with:
          host: anvil.works
          private-key: ${{ secrets.SSH_KEY }}
          private-key-name: anvil-key

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push with SSH forwarding
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/quik2007/phoenix_a3000_verify:latest
          ssh: default
